// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsgnhdidmw8hdiSQm-W_zfQcUp04aOdgM',
    appId: '1:451499560463:android:e277af98b87938ae6a1d7a',
    messagingSenderId: '451499560463',
    projectId: 'kuliku-3c03c',
    storageBucket: 'kuliku-3c03c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtMCTyNBSzCPh_Ojap5dGAi3aVQ_QRVHw',
    appId: '1:451499560463:ios:9b579fc7bc990bff6a1d7a',
    messagingSenderId: '451499560463',
    projectId: 'kuliku-3c03c',
    storageBucket: 'kuliku-3c03c.appspot.com',
    androidClientId: '451499560463-gpolbbtq3smad9h0cm8oou5c2pqr4adr.apps.googleusercontent.com',
    iosClientId: '451499560463-s3t70ji2ah3iqf66ao7s4105puekapsf.apps.googleusercontent.com',
    iosBundleId: 'com.kuliku.kuliku',
  );
}
